version: '3.7'

services:
  mysql:
    image: mysql:latest
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password 
    volumes:
      - "./data.sql:/docker-entrypoint-initdb.d/1.sql"
